// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    $('.module-footer').click(function(e) {
      var $footer;
      $footer = $(this);
      $footer.parent('.module').toggleClass('box-up');
      if ($footer.parent('.module').hasClass('box-up')) {
        return $footer.html($footer.attr('data-down'));
      } else {
        return $footer.html($footer.attr('data-up'));
      }
    });
    $('#share-btn').click(function(e) {
      return $('.share-box').show();
    });
    return $('.share-cancel-btn').click(function(e) {
      return $('.share-box').hide();
    });
  });

}).call(this);
