// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    console.log('superwolf');
    $('.module-footer').click(function(e) {
      console.log('supoerwolf');
      return $(this).parent('.module').toggleClass('box-up');
    });
    $('#share-btn').click(function(e) {
      return $('.share-box').show();
    });
    return $('.share-cancel-btn').click(function(e) {
      return $('.share-box').hide();
    });
  });

}).call(this);
