// Generated by CoffeeScript 1.6.2
(function() {
  var connect;

  connect = require('connect');

  connect().use(connect.logger()).use('/', connect["static"](__dirname + '/')).listen(9001);

}).call(this);
